"""site/vocab.json: the 1880-move vocabulary and the 16 square codes, generated from the frozen contract.

The browser tokenizer reads this file instead of re-deriving the vocabulary, so the page and Python can
never disagree on an index. `test_the_tracked_vocab_json_is_current` fails when the file is stale.
"""

import json
from pathlib import Path
from typing import Any

import chess

from blink.board import encode, moves, value

PIECE_LETTERS = {chess.QUEEN: "q", chess.ROOK: "r", chess.BISHOP: "b", chess.KNIGHT: "n"}


def build() -> dict[str, Any]:
    return {
        "about": (
            "Blink move vocabulary and square codes, generated by `blink export vocab` from "
            "blink/board/moves.py and blink/board/encode.py. Squares are 0..63 = file + 8 * rank "
            "(a1 = 0, h8 = 63), always in the side-to-move frame: Black's squares flip the rank (sq ^ 56)."
        ),
        "num_moves": moves.NUM_MOVES,
        "num_from_to": moves.NUM_FROM_TO,
        "from_to": [list(pair) for pair in moves.FROM_TO],
        "promo_pairs": [list(pair) for pair in moves.PROMO_PAIRS],
        "promo_pieces": [PIECE_LETTERS[piece] for piece in moves.PROMO_PIECES],
        "codes": {
            "empty": encode.EMPTY,
            "own": encode.OWN,
            "opp": encode.OPP,
            "own_castling_rook": encode.OWN_CASTLING_ROOK,
            "opp_castling_rook": encode.OPP_CASTLING_ROOK,
            "ep_square": encode.EP_SQUARE,
            "num_codes": encode.NUM_CODES,
        },
        "piece_order": [chess.piece_symbol(piece) for piece in chess.PIECE_TYPES],
        "num_bins": value.NUM_BINS,
    }


def render(data: dict[str, Any]) -> str:
    """Stable text: one key per line, the long pair lists kept on one line each."""
    lines = [f"  {json.dumps(key)}: {json.dumps(item, separators=(',', ':'))}" for key, item in data.items()]
    return "{\n" + ",\n".join(lines) + "\n}\n"


def write(path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(render(build()))
    return path
