{
  "url": "https://lichess.org/",
  "engine": {
    "dir": "C:/dev/blink-chess/.venv/Scripts",
    "name": "blink-uci.exe",
    "working_dir": "",
    "protocol": "uci",
    "ponder": false,
    "uci_ponder": false,
    "engine_options": {"model": "ship", "mode": "policy", "device": "cpu", "threads": 1, "priority": "below_normal", "log": "D:/blink/lichess/decisions-casual/{process}.jsonl"},
    "polyglot": {"enabled": false},
    "draw_or_resign": {
      "resign_enabled": false,
      "resign_for_egtb_minus_two": false,
      "offer_draw_enabled": false,
      "offer_draw_for_egtb_zero": false
    },
    "online_moves": {
      "chessdb_book": {"enabled": false},
      "lichess_cloud_analysis": {"enabled": false},
      "lichess_opening_explorer": {"enabled": false},
      "online_egtb": {"enabled": false}
    },
    "lichess_bot_tbs": {
      "syzygy": {"enabled": false},
      "gaviota": {"enabled": false}
    },
    "uci_options": {},
    "silence_stderr": false
  },
  "abort_time": 30,
  "quit_after_all_games_finish": true,
  "pgn_directory": "D:/blink/lichess/pgn-casual",
  "pgn_file_grouping": "game",
  "correspondence": {"ponder": false, "uci_ponder": false},
  "challenge": {
    "concurrency": 1,
    "games_reserved_for_humans": 0,
    "sort_by": "first",
    "preference": "none",
    "accept_bot": false,
    "only_bot": false,
    "variants": ["standard"],
    "time_controls": ["bullet", "blitz", "rapid"],
    "modes": ["casual"],
    "allow_list": ["itayco2"],
    "bullet_requires_increment": true,
    "max_simultaneous_games_per_user": 1
  },
  "matchmaking": {"allow_matchmaking": false}
}
