"""`blink site serve`: the page on http://127.0.0.1:<port>, never on another interface.

The host is hard-coded (no CLI override): no firewall prompt, no LAN exposure. Routes:
  /                     site/ (index.html, app.js, rules.js, worker.js, tokenizer.js, vocab.json, assets,
                        vendor/cm-chessboard), minus what layout.NOT_DEPLOYED keeps out of the page
  /vendor/ort/...       the three onnxruntime-web files layout.NPM_FILES lists, from site/node_modules
  /vendor/chess.js/...  chess.js's ESM build and its LICENSE, from site/node_modules
  /models/model.onnx    the --model file; /models/model.json its export card (or a minimal one)
Everything else, including site/node_modules itself, is a 404, so the local page loads exactly what
`blink site stage` deploys. Paths with '..' never resolve.
"""

import json
import sys
from dataclasses import dataclass
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import unquote, urlsplit

from blink.site import layout

HOST = "127.0.0.1"
DEFAULT_PORT = 8000
ORT_WASM_ENTRY = "ort.wasm.bundle.min.mjs"  # what `import "onnxruntime-web/wasm"` resolves to in a browser
MODEL_FILE = "model.onnx"
CARD_FILE = "model.json"
CONTENT_TYPES = {
    ".html": "text/html; charset=utf-8",
    ".js": "text/javascript; charset=utf-8",
    ".mjs": "text/javascript; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".json": "application/json; charset=utf-8",
    ".svg": "image/svg+xml",
    ".wasm": "application/wasm",
    ".onnx": "application/octet-stream",
    ".txt": "text/plain; charset=utf-8",
}


@dataclass(frozen=True)
class SiteConfig:
    site_dir: Path
    model: Path

    def npm_files(self) -> dict[str, Path]:
        return layout.npm_sources(self.site_dir)


def resolve_model(path: Path) -> Path:
    """The .onnx file to serve: `path` itself, or model.onnx inside the directory `path`."""
    candidate = path / MODEL_FILE if path.is_dir() else path
    if not candidate.is_file():
        raise FileNotFoundError(f"no ONNX model at {candidate} (run: blink export onnx --model <selector>)")
    return candidate


def _inside(root: Path, relative: str) -> Path | None:
    try:
        candidate = (root / relative).resolve()
        inside = candidate.is_file() and candidate.is_relative_to(root.resolve())
    except (OSError, ValueError):  # a NUL byte or a name the OS refuses is a 404, not a crash
        return None
    return candidate if inside else None


def model_card(model: Path) -> bytes | Path:
    """The export card beside the model, or a minimal one: the page fetches it and must not see a 404."""
    card = model.with_name(CARD_FILE)
    if card.is_file():
        return card
    return (json.dumps({"file": MODEL_FILE, "bytes": model.stat().st_size}, indent=2) + "\n").encode("utf-8")


def resolve_request(cfg: SiteConfig, raw_path: str) -> Path | bytes | None:
    """The file (or generated bytes) a request path maps to, or None for a 404."""
    parts = unquote(urlsplit(raw_path).path).replace("\\", "/").split("/")
    if any(part in (".", "..") or ":" in part for part in parts):
        return None
    relative = "/".join(part for part in parts if part) or "index.html"
    if relative == f"models/{MODEL_FILE}":
        return cfg.model
    if relative == f"models/{CARD_FILE}":
        return model_card(cfg.model)
    if not layout.is_deployed(relative):
        return None
    if layout.is_npm_route(relative):
        source = cfg.npm_files().get(relative)
        return source if source is not None and source.is_file() else None
    return _inside(cfg.site_dir, relative)


def content_type(name: str) -> str:
    return CONTENT_TYPES.get(Path(name).suffix.lower(), "application/octet-stream")


class _Handler(BaseHTTPRequestHandler):
    server_version = "BlinkSite/1"
    server: "SiteServer"

    def do_GET(self) -> None:
        self._respond(send_body=True)

    def do_HEAD(self) -> None:
        self._respond(send_body=False)

    def _respond(self, send_body: bool) -> None:
        target = resolve_request(self.server.cfg, self.path)
        if target is None:
            self.send_error(404)
            return
        body = target if isinstance(target, bytes) else target.read_bytes()
        name = CARD_FILE if isinstance(target, bytes) else target.name
        self.send_response(200)
        self.send_header("Content-Type", content_type(name))
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-cache")
        self.send_header("X-Content-Type-Options", "nosniff")
        self.end_headers()
        if send_body:
            self.wfile.write(body)

    def log_message(self, format: str, *args) -> None:
        if self.server.verbose:
            sys.stderr.write(f"{self.address_string()} {format % args}\n")


class SiteServer(ThreadingHTTPServer):
    allow_reuse_address = False  # on Windows, SO_REUSEADDR would let a second server share the port
    daemon_threads = True

    def __init__(self, cfg: SiteConfig, port: int, verbose: bool = False) -> None:
        self.cfg = cfg
        self.verbose = verbose
        super().__init__((HOST, port), _Handler)


def make_server(cfg: SiteConfig, port: int = DEFAULT_PORT, verbose: bool = False) -> SiteServer:
    return SiteServer(cfg, port, verbose)


def run(cfg: SiteConfig, port: int = DEFAULT_PORT) -> None:
    server = make_server(cfg, port, verbose=True)
    url = f"http://{HOST}:{server.server_address[1]}/"
    print(f"serving {cfg.site_dir} with model {cfg.model} at {url} (loopback only; Ctrl+C stops)", flush=True)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()
