"""The lichess-bot configs, generated from the tracked templates and checked against the plan (P9).

    blink lichess config --model SELECTOR --mode policy|value [--sha SHA] [--casual-model SELECTOR]
    blink lichess check-config --config PATH [--kind rated|casual] [--results results/results.json]

Two files come from deploy/lichess: `config.yml` (the rated bot, gate G7) from config.template.yml and
`config.casual.yml` (the G5 casual smoke) from config.casual.yml. Generation copies a template, points
engine_options at the model selector and mode (lichess-bot passes each entry to blink-uci as
--key=value), and adds a `blink:` block recording the kind, model, mode and, for the rated bot, the
sha256 of the shipped weights file. lichess-bot ignores keys it does not know.

The files are JSON, which YAML reads as the same mapping (the project has no YAML library, and JSON
cannot hide a tab or a stray anchor). They never hold the token: lichess-bot takes it from
LICHESS_BOT_TOKEN, which only Itay's start-bot.ps1 sets.

`problems()` is the one check behind check-config, the generator and the tests: every lookup off
(config_check), abort_time 30, concurrency under challenge, only UCI options blink-uci declares,
engine options blink-uci accepts, the plan's rated or casual settings, and (rated only) the shipped
sha and mode. The casual smoke runs the preview model during P7, so it is exempt from the ship check.
"""

import contextlib
import copy
import hashlib
import io
import json
import re
from collections.abc import Callable, Iterable, Mapping
from dataclasses import dataclass
from pathlib import Path

from blink.lichess import config_check
from blink.report.results_schema import Shipped
from blink.train.atomic import write_text_atomic

REPO_ROOT = Path(__file__).resolve().parents[2]
TEMPLATE_DIR = REPO_ROOT / "deploy" / "lichess"
TEMPLATES = {"rated": "config.template.yml", "casual": "config.casual.yml"}
OUTPUT_NAMES = {"rated": "config.yml", "casual": "config.casual.yml"}
KINDS = ("rated", "casual")
MODES = ("policy", "value")
DEFAULT_OUT_DIR = Path("D:/blink-bot")
PROVENANCE = "blink"
NOTE = "generated by `blink lichess config` from the tracked template; never add the token here"
SHA = re.compile(r"^[0-9a-f]{7,64}$")
TOKEN = re.compile(r"(lip|lio)_[A-Za-z0-9]{16,}")

COMMON_RULES: dict[tuple[str, ...], object] = {
    ("abort_time",): 30,
    ("engine", "protocol"): "uci",
    ("engine", "name"): "blink-uci.exe",
    ("engine", "draw_or_resign", "resign_enabled"): False,
    ("engine", "draw_or_resign", "offer_draw_enabled"): False,
    ("challenge", "variants"): ["standard"],
    ("challenge", "max_simultaneous_games_per_user"): 1,
}
RATED_RULES = {
    **COMMON_RULES,
    ("engine", "engine_options", "device"): "cuda",
    ("challenge", "concurrency"): 2,
    ("challenge", "games_reserved_for_humans"): 1,
    ("challenge", "preference"): "human",
    ("challenge", "bullet_requires_increment"): True,
    ("challenge", "accept_bot"): True,
    ("challenge", "time_controls"): ["blitz"],
    ("challenge", "modes"): ["rated"],
    ("challenge", "allow_list"): [],
    ("matchmaking", "allow_matchmaking"): True,
    ("matchmaking", "challenge_mode"): "rated",
    ("matchmaking", "challenge_variant"): "standard",
    ("matchmaking", "challenge_initial_time"): [180, 300],
    ("matchmaking", "challenge_increment"): [0, 2, 3],
    ("matchmaking", "challenge_timeout"): 2,
    ("matchmaking", "opponent_rating_difference"): 300,
    ("matchmaking", "challenge_filter"): "fine",
    ("pgn_directory",): "D:/blink/lichess/pgn",
}
CASUAL_RULES = {
    **COMMON_RULES,
    ("engine", "engine_options", "device"): "cpu",
    ("challenge", "allow_list"): ["itayco2"],
    ("challenge", "concurrency"): 1,
    ("challenge", "games_reserved_for_humans"): 0,
    ("challenge", "accept_bot"): False,
    ("challenge", "modes"): ["casual"],
    ("challenge", "time_controls"): ["bullet", "blitz", "rapid"],
    ("matchmaking", "allow_matchmaking"): False,
}
RULES = {"rated": RATED_RULES, "casual": CASUAL_RULES}


class ConfigError(ValueError):
    """A config cannot be generated or read."""


@dataclass(frozen=True)
class BotSpec:
    model: str
    mode: str
    sha: str | None = None  # the shipped weights' sha256 (or a prefix); rated only
    casual_model: str | None = None  # the preview model for the casual smoke; defaults to model


# ---------------------------------------------------------------- reading and writing


def load_config(path: Path) -> dict:
    text = Path(path).read_text(encoding="utf-8")
    try:
        return json.loads(text)
    except json.JSONDecodeError as exc:
        raise ConfigError(
            f"{path} is not the JSON form of YAML this project writes ({exc}); regenerate it"
        ) from exc


def dump_config(config: Mapping) -> str:
    return json.dumps(config, indent=2, ensure_ascii=True) + "\n"


def _lookup(config: Mapping, path: tuple[str, ...]) -> tuple[bool, object]:
    node: object = config
    for key in path:
        if not isinstance(node, Mapping) or key not in node:
            return False, None
        node = node[key]
    return True, node


def _same(actual: object, expected: object) -> bool:
    """Equal as JSON, so true is not 1 and [180, 300] is not [300, 180]."""
    return json.dumps(actual, sort_keys=True) == json.dumps(expected, sort_keys=True)


# ---------------------------------------------------------------- the engine's own UCI options


def parse_uci_options(lines: Iterable[str]) -> frozenset[str]:
    """Option names from `option name <name> type ...` lines of a UCI handshake."""
    prefix = "option name "
    return frozenset(
        line[len(prefix) :].split(" type ", 1)[0].strip() for line in lines if line.startswith(prefix)
    )


def declared_uci_options() -> frozenset[str]:
    """What blink-uci itself answers to `uci` (no model is loaded for that)."""
    from blink import uci

    out = io.StringIO()
    uci.UciEngine(lambda: None, out).handle("uci")
    return parse_uci_options(out.getvalue().splitlines())


# ---------------------------------------------------------------- the checks


def _rule_problems(config: Mapping, rules: Mapping[tuple[str, ...], object]) -> list[str]:
    found = []
    for path, expected in rules.items():
        present, actual = _lookup(config, path)
        if not present or not _same(actual, expected):
            shown = json.dumps(actual) if present else "nothing"
            found.append(f"{'.'.join(path)} must be {json.dumps(expected)}, found {shown}")
    return found


def _strings(node: object, path: tuple[str, ...] = ()) -> Iterable[tuple[str, str]]:
    if isinstance(node, Mapping):
        for key, value in node.items():
            yield from _strings(value, (*path, str(key)))
    elif isinstance(node, list):
        for index, value in enumerate(node):
            yield from _strings(value, (*path, str(index)))
    elif isinstance(node, str):
        yield ".".join(path), node


def _token_problems(config: Mapping) -> list[str]:
    found = (
        ["token: a config never holds the token (lichess-bot reads LICHESS_BOT_TOKEN)"]
        if "token" in config
        else []
    )
    found += [f"token-like text at {where}" for where, text in _strings(config) if TOKEN.search(text)]
    return found


def _placement_problems(config: Mapping) -> list[str]:
    return [
        f"{key} is set at the top level; lichess-bot reads only challenge.{key}"
        for key in ("concurrency", "games_reserved_for_humans")
        if key in config
    ]


def _uci_option_problems(config: Mapping, declared: frozenset[str]) -> list[str]:
    options = (config.get("engine") or {}).get("uci_options") or {}
    return [
        f"engine.uci_options.{name} is not an option blink-uci declares"
        for name in options
        if name not in declared
    ]


def _engine_flag_problems(config: Mapping) -> list[str]:
    from blink import uci

    options = (config.get("engine") or {}).get("engine_options") or {}
    found = [
        f"engine.engine_options.{key} must be set"
        for key in ("model", "mode", "device", "log")
        if key not in options
    ]
    if "random" in options:
        found.append("engine.engine_options.random plays a random network")
    flags = [f"--{key}={value}" if value is not None else f"--{key}" for key, value in options.items()]
    with contextlib.redirect_stderr(io.StringIO()) as err:
        try:
            uci.build_parser().parse_args(flags)
        except SystemExit:
            found.append(f"engine.engine_options do not parse as blink-uci flags: {err.getvalue().strip()}")
    return found


def sha_match(one: str | None, other: str | None) -> bool:
    """Two sha256 hex strings, either of which may be a prefix (7 digits or more), name the same file."""
    if not one or not other:
        return False
    a, b = one.lower(), other.lower()
    return min(len(a), len(b)) >= 7 and (a.startswith(b) or b.startswith(a))


def _ship_problems(config: Mapping, shipped: Shipped | None, weights_sha: str | None) -> list[str]:
    stamp = config.get(PROVENANCE) or {}
    options = (config.get("engine") or {}).get("engine_options") or {}
    sha, mode = stamp.get("sha"), options.get("mode")
    found = (
        []
        if sha and SHA.match(str(sha))
        else ["blink.sha is missing: generate the config with `blink lichess config`"]
    )
    for key in ("model", "mode"):
        if stamp.get(key) != options.get(key):
            found.append(f"blink.{key} {stamp.get(key)!r} is not the engine's {key} {options.get(key)!r}")
    if shipped is not None and shipped.mode != mode:
        found.append(f"the engine runs mode {mode!r} but the shipped mode is {shipped.mode!r}")
    if shipped is not None and sha and not sha_match(shipped.sha, sha):
        found.append(f"blink.sha {sha} is not the shipped sha {shipped.sha}")
    if weights_sha is not None and sha and not sha_match(weights_sha, sha):
        found.append(f"the weights file's sha256 {weights_sha[:12]} is not blink.sha {str(sha)[:12]}")
    return found


def problems(
    config: Mapping,
    kind: str,
    declared: frozenset[str],
    shipped: Shipped | None = None,
    weights_sha: str | None = None,
) -> list[str]:
    """Every way `config` breaks the plan for a `kind` bot; empty when it is fit to run."""
    if kind not in RULES:
        return [f"unknown config kind {kind!r}: rated or casual"]
    found = list(config_check.lookup_problems(config))
    found += _token_problems(config)
    found += _placement_problems(config)
    found += _rule_problems(config, RULES[kind])
    found += _uci_option_problems(config, declared)
    found += _engine_flag_problems(config)
    if kind == "rated":
        found += _ship_problems(config, shipped, weights_sha)
    return found


# ---------------------------------------------------------------- weights and the shipped sha


def file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def weights_file(selector: str) -> Path | None:
    """The weights file a selector loads, or None when it cannot be found (or torch is absent)."""
    try:
        from blink.model.loading import resolve_selector
    except ImportError:
        return None
    try:
        path, _ = resolve_selector(selector)
    except (ValueError, FileNotFoundError):
        return None
    return path if path.is_file() else None


def shipped_sha(model: str, given: str | None, resolve: Callable[[str], Path | None]) -> str:
    """The sha256 the rated config records: the weights file's, checked against --sha when both exist."""
    path = resolve(model)
    actual = file_sha256(path) if path is not None else None
    if given is None:
        if actual is None:
            raise ConfigError(f"cannot find the weights file for {model!r}; pass the shipped --sha")
        return actual
    given = given.lower()
    if not SHA.match(given):
        raise ConfigError(f"--sha {given!r} must be 7 to 64 hex digits")
    if actual is not None and not actual.startswith(given):
        raise ConfigError(f"--sha {given} does not match {path} (sha256 {actual[:12]})")
    return actual or given


# ---------------------------------------------------------------- generation


def render(template: Mapping, kind: str, model: str, mode: str, sha: str | None) -> dict:
    """A new config: the template with the engine pointed at `model` in `mode`, and its provenance."""
    config = copy.deepcopy(dict(template))
    engine = dict(config.get("engine") or {})
    engine["engine_options"] = {**(engine.get("engine_options") or {}), "model": model, "mode": mode}
    stamp = {"kind": kind, "model": model, "mode": mode, "template": TEMPLATES[kind], "note": NOTE}
    return {**config, "engine": engine, PROVENANCE: {**stamp, "sha": sha} if kind == "rated" else stamp}


def _render_all(spec: BotSpec, kinds: Iterable[str], templates: Path, resolve) -> dict[str, dict]:
    configs = {}
    for kind in kinds:
        template = load_config(Path(templates) / TEMPLATES[kind])
        if kind == "rated":
            configs[kind] = render(
                template, kind, spec.model, spec.mode, shipped_sha(spec.model, spec.sha, resolve)
            )
        else:
            configs[kind] = render(template, kind, spec.casual_model or spec.model, spec.mode, None)
    return configs


def generate(
    spec: BotSpec,
    out_dir: Path = DEFAULT_OUT_DIR,
    kinds: Iterable[str] = KINDS,
    templates: Path = TEMPLATE_DIR,
    resolve: Callable[[str], Path | None] = weights_file,
) -> dict[str, Path]:
    """Write config.yml and/or config.casual.yml into `out_dir`; nothing is written unless all pass."""
    kinds = tuple(kinds)
    if spec.mode not in MODES:
        raise ConfigError(f"--mode must be one of {MODES}, got {spec.mode!r}")
    if unknown := [k for k in kinds if k not in KINDS]:
        raise ConfigError(f"unknown config kinds {unknown}: {KINDS}")
    configs = _render_all(spec, kinds, templates, resolve)
    declared = declared_uci_options()
    for kind, config in configs.items():
        if found := problems(config, kind, declared):
            raise ConfigError(f"the generated {kind} config breaks {len(found)} rules: " + "; ".join(found))
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    written = {}
    for kind, config in configs.items():
        write_text_atomic(out_dir / OUTPUT_NAMES[kind], dump_config(config))
        written[kind] = out_dir / OUTPUT_NAMES[kind]
    return written


# ---------------------------------------------------------------- check-config on a file


@dataclass(frozen=True)
class CheckReport:
    kind: str
    problems: tuple[str, ...]
    notes: tuple[str, ...]


def _shipped_from(results: Path | None) -> tuple[Shipped | None, str | None]:
    if results is None:
        return None, "shipped model not compared (--results none)"
    if not Path(results).is_file():
        return None, f"no {results} yet: the shipped sha and mode were not compared"
    from blink.report.results_schema import from_json

    shipped = from_json(Path(results).read_text(encoding="utf-8")).shipped
    return shipped, None if shipped else f"{results} names no shipped model yet: not compared"


def check_file(
    path: Path,
    kind: str | None = None,
    results: Path | None = None,
    resolve: Callable[[str], Path | None] = weights_file,
) -> CheckReport:
    config = load_config(path)
    kind = kind or (config.get(PROVENANCE) or {}).get("kind") or ""
    notes = []
    shipped, note = _shipped_from(results) if kind == "rated" else (None, None)
    notes += [note] if note else []
    weights_sha = None
    engine = config.get("engine") or {}
    if kind == "rated":
        weights = resolve(str((engine.get("engine_options") or {}).get("model", "")))
        weights_sha = file_sha256(weights) if weights is not None else None
        notes += (
            [f"weights {weights}: sha256 {weights_sha[:12]}"]
            if weights
            else ["weights file not found: not hashed"]
        )
    exe = Path(str(engine.get("dir", ""))) / str(engine.get("name", ""))
    notes += [] if exe.is_file() else [f"engine {exe} does not exist on this machine (lichess-bot needs it)"]
    found = problems(config, kind, declared_uci_options(), shipped=shipped, weights_sha=weights_sha)
    return CheckReport(kind=kind, problems=tuple(found), notes=tuple(notes))
